/* Progressive enhancements for the continuous-scroll teaching archive. */
(() => {
'use strict';
if('scrollRestoration' in history)history.scrollRestoration='manual';
// Local QA observations only; no telemetry is transmitted or persisted.
if('PerformanceObserver' in window){let cls=0;for(const type of ['largest-contentful-paint','layout-shift','longtask']){try{new PerformanceObserver(list=>{for(const entry of list.getEntries()){if(type==='largest-contentful-paint')document.documentElement.dataset.lcpMs=String(Math.round(entry.startTime));else if(type==='layout-shift'&&!entry.hadRecentInput){cls+=entry.value;document.documentElement.dataset.cls=String(cls);}else if(type==='longtask')document.documentElement.dataset.maxTaskMs=String(Math.max(Number(document.documentElement.dataset.maxTaskMs||0),Math.round(entry.duration)));}}).observe({type,buffered:true});}catch{}}}
const panels=[...document.querySelectorAll('.panel')],canvas=document.getElementById('canvas'),indexDialog=document.getElementById('lesson-index'),lightbox=document.getElementById('lightbox'),largeImage=document.getElementById('large-image'),reduceMotion=matchMedia('(prefers-reduced-motion: reduce)');
let current=0,zoom=1,opener=null,starting=true,navigationLock=true,lastWidth=canvas.clientWidth,lastHeight=innerHeight,activeObserver;
const fit=()=>{const scale=canvas.clientWidth/1920;canvas.style.setProperty('--scale',scale);canvas.style.setProperty('--tap-height',`${44/scale}px`);};fit();
const select=index=>{current=index;document.getElementById('current-page').textContent=String(index+1).padStart(2,'0');document.getElementById('index-open').setAttribute('aria-label',`目录${String(index+1).padStart(2,'0')}，打开课堂目录`);document.getElementById('progress').style.transform=`scaleX(${(index+1)/panels.length})`;if(!starting)history.replaceState(null,'',`#${index+1}`);try{localStorage.setItem('ip-studio-page',String(index+1));}catch{}};
function observeReading(){activeObserver?.disconnect();activeObserver=new IntersectionObserver(entries=>{if(navigationLock)return;const active=entries.filter(e=>e.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top)[0];if(active)select(Number(active.target.dataset.index));},{rootMargin:`-${Math.round(innerHeight*.12)}px 0px -${Math.round(innerHeight*.75)}px 0px`});if(!navigationLock)panels.forEach(p=>activeObserver.observe(p));}observeReading();
const revealObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-entered');revealObserver.unobserve(e.target);}});},{threshold:.06});panels.filter(p=>p.classList.contains('native-panel')).forEach(p=>revealObserver.observe(p));
function jump(page){navigationLock=true;activeObserver.disconnect();const panel=panels[Math.max(0,Math.min(panels.length-1,page-1))];fit();panel.scrollIntoView({behavior:'instant',block:'start'});select(Number(panel.dataset.index));requestAnimationFrame(()=>requestAnimationFrame(()=>{navigationLock=false;panels.forEach(p=>activeObserver.observe(p));}));}
new ResizeObserver(()=>{const width=canvas.clientWidth;if(width===lastWidth)return;lastWidth=width;fit();observeReading();if(!starting)jump(current+1);}).observe(canvas);
window.addEventListener('resize',()=>{if(innerHeight!==lastHeight){lastHeight=innerHeight;observeReading();}},{passive:true});
function openDialog(dialog,button){opener=button;dialog.showModal();}
[indexDialog,lightbox].forEach(dialog=>{dialog.addEventListener('close',()=>{if(opener?.isConnected)opener.focus({preventScroll:true});if(dialog===lightbox){largeImage.removeAttribute('src');largeImage.style.width='';}});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});});
const applyZoom=()=>{largeImage.style.width=zoom===1?'':`${zoom*100}%`;largeImage.classList.toggle('zoomed',zoom>1);document.getElementById('zoom-level').textContent=zoom===1?'适应窗口':`${Math.round(zoom*100)}%`;};
document.addEventListener('click',event=>{
const imageButton=event.target.closest('[data-image]');if(imageButton){largeImage.src=imageButton.dataset.image;largeImage.alt=imageButton.dataset.caption||'角色设计图像';document.getElementById('large-caption').textContent=largeImage.alt;document.getElementById('lightbox-title').textContent=largeImage.alt;zoom=1;applyZoom();openDialog(lightbox,imageButton);return;}
const close=event.target.closest('[data-close]');if(close){document.getElementById(close.dataset.close).close();return;}
const chapter=event.target.closest('[data-jump]');if(chapter){event.preventDefault();indexDialog.close();history.replaceState(null,'',chapter.hash);jump(Number(chapter.dataset.jump));return;}
const anchor=event.target.closest('[data-anchor]');if(anchor){const body=anchor.closest('.anchor-body'),image=body.querySelector('.anchor-image');body.querySelectorAll('[data-anchor]').forEach(b=>b.setAttribute('aria-pressed',String(b===anchor)));image.dataset.active=anchor.dataset.anchor;return;}
const test=event.target.closest('[data-test]');if(test){const body=test.closest('.test-body'),figure=body.querySelector('.test-image');if(test.dataset.test==='small'){test.setAttribute('aria-pressed',String(test.getAttribute('aria-pressed')!=='true'));figure.classList.toggle('is-small');}else{figure.classList.toggle('is-gray',test.dataset.test==='gray');body.querySelectorAll('[data-test]:not([data-test="small"])').forEach(b=>b.setAttribute('aria-pressed',String(b===test)));}body.querySelector('figcaption').textContent=`当前观察：${figure.classList.contains('is-gray')?'灰度':'原色'} · ${figure.classList.contains('is-small')?'缩小尺寸':'完整尺寸'}`;}
});
document.getElementById('index-open').addEventListener('click',e=>{openDialog(indexDialog,e.currentTarget);document.getElementById('lesson-search').focus();});
const search=document.getElementById('lesson-search'),results=document.getElementById('search-results'),chapterList=document.getElementById('chapter-list');
search.addEventListener('input',()=>{const term=search.value.trim().toLocaleLowerCase();results.replaceChildren();results.hidden=!term;chapterList.hidden=Boolean(term);if(!term)return;const matches=panels.filter(p=>p.getAttribute('aria-label').toLocaleLowerCase().includes(term));if(!matches.length){const empty=document.createElement('p');empty.className='search-empty';empty.textContent='未找到相关页，试试角色、轮廓或色彩。';results.append(empty);return;}matches.forEach(panel=>{const link=document.createElement('a'),number=document.createElement('span');link.href=`#${panel.id}`;link.dataset.jump=panel.id;number.textContent=String(Number(panel.id)).padStart(2,'0');link.append(number,document.createTextNode(panel.getAttribute('aria-label').replace(/^\d+ · /,'')));results.append(link);});});
document.getElementById('zoom-in').addEventListener('click',()=>{zoom=Math.min(3,zoom+.5);applyZoom();});document.getElementById('zoom-out').addEventListener('click',()=>{zoom=Math.max(1,zoom-.5);applyZoom();});document.getElementById('zoom-reset').addEventListener('click',()=>{zoom=1;applyZoom();});
window.addEventListener('hashchange',()=>{if(/^#\d+$/.test(location.hash))jump(Number(location.hash.slice(1)));});requestAnimationFrame(()=>{jump(/^#\d+$/.test(location.hash)?Number(location.hash.slice(1)):1);starting=false;});
window.lessonDebug={get count(){return panels.length;},get index(){return current;},go:i=>jump(i+1)};
})();
