const fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..'),ctx={window:{}};
for(const f of ['content.js','original-pages.js','media-manifest.js'])vm.runInNewContext(fs.readFileSync(path.join(root,f),'utf8'),ctx);
const lesson=ctx.window.LESSON,media=ctx.window.STUDIO_MEDIA,originals=ctx.window.STUDIO_ORIGINAL;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>String(n).padStart(2,'0');
function img(src,alt,cls='',eager=false){const m=media[src]||{src,width:1920,height:1080};return `<img src="${m.src}" width="${m.width}" height="${m.height}" alt="${esc(alt)}" class="${cls}" loading="${eager?'eager':'lazy'}" decoding="${eager?'sync':'async'}"${eager?' fetchpriority="high"':''}>`;}
function zoom(src,label='放大图像',alt=''){return `<button class="image-open" data-image="${esc(src)}" data-caption="${esc(alt)}" aria-label="${esc(alt?label+'：'+alt:label)}">${label}<span aria-hidden="true">↗</span></button>`;}
const article=(r,j)=>`<article class="item"><span class="item-number" aria-hidden="true">${num(j+1)}</span><h3>${esc(r[0])}</h3><p>${esc(r[1])}</p></article>`;
function header(s){return `<header class="section-head"><p class="section-kicker">${esc(s.chapter)}</p><h2>${esc(s.title)}</h2>${s.lead?`<p class="lead">${esc(s.lead)}</p>`:''}</header>`;}
function footer(s,i){return `<footer class="panel-footer"><span>角色观察档案 <span class="footer-separator">/</span> ${esc(s.chapter)}</span><span class="folio">${num(i+1)} <small>/ 79</small></span></footer>`;}
function table(s){const h=s.items[0];return `<div class="editorial-table cols-${h.length}" role="table" aria-label="${esc(s.title)}"><div class="table-head" role="row">${h.map(x=>`<span role="columnheader">${esc(x)}</span>`).join('')}</div>${s.items.slice(1).map((row,j)=>`<div class="table-row" role="row">${row.map((v,k)=>`<div role="${k?'cell':'rowheader'}" data-label="${esc(h[k])}">${k?'':`<span class="row-number" aria-hidden="true">${num(j+1)}</span>`}${esc(v)}</div>`).join('')}</div>`).join('')}</div>`;}
const chapterInfo={6:['01','STORY','贴合角色故事','让设计为叙事服务'],8:['02','STYLE','符合美术风格','确保整体视觉统一'],10:['03','PERFORMANCE','适配配音人设',''],11:['04','CASE STUDY','巴斯光年 · 案例拆解',''],35:['05','ORIGINAL WORKFLOW','从探索到交付','']};
function render(s,i){let c='',type=s.kind,raw=false;
if(s.original===1){type='cover';c=`<div class="cover-copy"><p class="cover-meta"><span>ICUC · IP DESIGN</span><span>第一节课</span></p><p class="cover-question">QUESTION / WHAT IS<br>CHARACTER CONCEPT DESIGN?</p><h1>角色<br><span>概念设计</span></h1><p class="cover-sub">从角色内核，到被记住的形象。</p><a class="begin-link" href="#2">开始观察 <span aria-hidden="true">↓</span></a></div><figure class="cover-art">${img('assets/media/image10.png','《光年正传》中巴斯光年的三维角色设计，正面、侧面与背面。','',true)}<figcaption>BUZZ LIGHTYEAR<br><span>轮廓 / 色彩 / 身份符号</span></figcaption><span class="art-cross cross-a" aria-hidden="true"></span><span class="art-cross cross-b" aria-hidden="true"></span></figure><span class="cover-serial" aria-hidden="true">01</span>${zoom(s.image,'查看原页',s.title)}`;}
else if(chapterInfo[s.original]){type='chapter';let[n,en,title,sub]=chapterInfo[s.original];c=`<div class="chapter-copy"><p class="section-kicker">${esc(s.chapter)}</p><p class="chapter-en">${en}</p><h2>${title}</h2>${sub?`<p class="lead">${sub}</p>`:''}<a class="chapter-next" href="#${i+2}">继续观察 <span aria-hidden="true">↓</span></a></div><span class="chapter-number" aria-hidden="true">${n}</span><div class="chapter-rule" aria-hidden="true"></div>${zoom(s.image,'查看原页',s.title)}`;}
else if(s.original===5){type='principles';c=`${header(s)}<div class="principle-map"><svg viewBox="0 0 1300 650" aria-hidden="true"><path d="M650 85 L160 535 L1140 535 Z" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="650" cy="300" r="65" fill="none" stroke="currentColor" stroke-width="2"/></svg><div class="principle-node node-story"><span>01 / STORY</span><h3>贴合角色故事</h3></div><div class="principle-node node-style"><span>02 / STYLE</span><h3>符合美术风格</h3></div><div class="principle-node node-performance"><span>03 / PERFORMANCE</span><h3>适配配音人设</h3></div><span class="map-center">角色</span></div><p class="map-caption">这三大原则相互关联、缺一不可，是判断人物概念设计是否合格的关键标准。</p>${zoom(s.image,'查看原页',s.title)}`;}
else if(originals[s.original]){const o=originals[s.original];type=o.layout;
if(type==='definition')c=`<header class="section-head"><p class="section-kicker">CHARACTER CONCEPT DESIGN</p><h2>将文字想象<br>转化为视觉形象。</h2></header><div class="definition-body"><div class="definition-main"><span class="label">${o.items[0][0]}</span><p>${esc(o.items[0][1])}</p></div><div class="definition-details">${o.items.slice(1).map(article).join('')}</div></div>`;
else if(type==='criteria')c=`<header class="section-head"><p class="section-kicker">角色概念设计</p><h2>${o.title}</h2></header><div class="criteria-body"><div class="criteria-visual" aria-hidden="true"><div class="shape circle"></div><div class="shape square"></div><div class="shape triangle"></div><p>SHAPE → IDENTITY → MOTION</p></div><div class="criteria-list">${o.items.map(article).join('')}</div></div>`;
else if(type==='story')c=`<header class="section-head"><p class="section-kicker">原则一 · 贴合角色故事</p><h2>${o.title}</h2></header><div class="story-body"><figure>${img(s.image,'原课件中的宇航员与军官：服饰、装备和身份的对照。')}<figcaption>身份：${o.identityLabels.join(' / ')}</figcaption></figure><div>${o.items.map(article).join('')}</div></div>`;
else c=`<header class="section-head"><p class="section-kicker">原则二 · 符合美术风格</p><h2>${o.title}</h2></header><div class="style-rules">${o.items.map(article).join('')}</div><div class="style-band" aria-hidden="true"><span>世界规则</span><i></i><span>角色比例</span><i></i><span>环境关系</span></div>`;
c+=zoom(s.image,'查看原页',s.title);}
else if(type==='raw'){raw=true;c=`<figure class="source-page">${img(s.image,`${s.title}，原课件第${s.original}页`)}<figcaption class="sr-only">${esc(s.title)}</figcaption></figure><div class="source-actions">${zoom(s.image,'放大原页',s.title)}${s.animation?zoom(s.animation,'查看动态图',s.title):''}</div>`;}
else if(i===15){type='anchor-lab';c=`${header(s)}<div class="anchor-body"><figure class="anchor-image" data-active="0">${img(s.image,'巴斯光年的背面、侧面与正面三视图；识别线索标注在右侧正面角色上。')}<span class="anchor-ring badge-ring" aria-hidden="true"></span><span class="anchor-ring color-ring" aria-hidden="true"></span><span class="anchor-ring helmet-ring" aria-hidden="true"></span><span class="anchor-image-caption">识别线索 / 三视图观察</span>${zoom(s.image,'查看完整图',s.title)}</figure><div class="anchor-list" aria-label="选择识别线索">${s.items.map((r,j)=>`<button class="anchor-choice" data-anchor="${j}" aria-pressed="${j===0}"><span class="item-number">${num(j+1)}</span><span><strong>${esc(r[0])}</strong><span class="anchor-description">${esc(r[1])}</span>${j===1?'<span class="swatches" aria-hidden="true"><i></i><i></i><i></i></span>':''}</span><span class="choice-arrow" aria-hidden="true">↗</span></button>`).join('')}</div></div>`;}
else if(type==='matrix')c=header(s)+table(s);
else if(type==='flow'){c=header(s)+`<div class="process ${s.items.length===3?'three-steps':''}">${s.items.map((r,j)=>`<article class="process-step"><span class="process-number">${num(j+1)}</span><span class="process-line" aria-hidden="true"></span><h3>${esc(r[0])}</h3><p>${esc(r[1])}</p></article>`).join('')}</div>`;if(i===9)c+='<div class="detail-sizes" aria-hidden="true"><i></i><i></i><i></i></div>';}
else if(type==='compare')c=header(s)+`<div class="comparison">${s.items.map(article).join('')}</div>${i===12?'<div class="comparison-axis" aria-hidden="true"><span>完整角色</span><i></i><span>独立符号</span></div>':''}`;
else if(type==='split')c=header(s)+`<div class="study-split"><figure class="study-image">${img(s.image,s.title+'：原课件中的角色探索参考')}${zoom(s.image,'放大图像',s.title)}</figure><div class="study-list">${s.items.map(article).join('')}</div></div>`;
else if(type==='compare3')c=header(s)+`<div class="test-body"><figure class="test-figure"><div class="test-image">${img(s.image,'原课件中的巴斯设计探索，用于原色、灰度与缩小识别测试。')}</div><figcaption id="test-caption">当前观察：原色 · 完整尺寸</figcaption><div class="test-controls" aria-label="图像观察条件"><button data-test="color" aria-pressed="true">原色</button><button data-test="gray" aria-pressed="false">去色相</button><button data-test="small" aria-pressed="false">缩小观察</button></div></figure><div class="study-list">${s.items.map(article).join('')}</div></div>`;
else c=header(s)+`<div class="concepts${i===29?' shape-concepts':''}">${s.items.map((r,j)=>i===29?`<div class="shape-unit"><div class="shape ${['circle','square','triangle'][j]}" aria-hidden="true"></div>${article(r,j)}</div>`:article(r,j)).join('')}</div>`;
if(s.source)c+=`<a class="reference" href="${esc(s.source[1])}" target="_blank" rel="noopener noreferrer">参考：${esc(s.source[0])} <span aria-hidden="true">↗</span></a>`;
return `<section class="panel ${raw?'source-panel':'native-panel'} ${type}-panel${i===76?' dense-panel':''}" id="${i+1}" data-index="${i}" data-original="${s.original||''}" data-kind="${type}" aria-label="${num(i+1)} · ${esc(s.title)}"><div class="sheet ${type}-sheet">${c}${raw?'':footer(s,i)}</div></section>`;}
const chapters=[['01','角色概念设计',1,'定义、视觉识别与记忆锚点'],['02','三大核心原则',18,'故事、风格与表演'],['03','贴合角色故事',20,'身份、目标与成长'],['04','符合美术风格',28,'形状、色彩与世界观'],['05','适配配音人设',33,'表情、身体与声音'],['06','巴斯光年案例',35,'从观察到设计解读'],['07','原创设计流程',61,'探索、收敛与交付']];
const html=`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#22366f"><meta name="description" content="IP角色设计课堂：从角色内核、视觉识别与记忆锚点，到巴斯光年案例拆解和完整设计流程。"><title>角色观察档案｜ICUC IP DESIGN</title><link rel="icon" type="image/svg+xml" href="favicon.svg"><link rel="preload" as="image" href="assets/optimized/image10.webp" fetchpriority="high"><link rel="preload" as="font" type="font/woff2" href="assets/fonts/space-grotesk-latin-variable.woff2" crossorigin><link rel="stylesheet" href="style.css?v=11"><script src="app.js?v=11" defer></script></head>
<body><a class="skip-link" href="#2">跳过开场，阅读课程</a><main id="canvas">${lesson.map(render).join('\n')}</main>
<div class="reading-progress" aria-hidden="true"><i id="progress"></i></div><button class="index-trigger" id="index-open" aria-haspopup="dialog" aria-label="目录01，打开课堂目录"><span class="index-icon" aria-hidden="true"><i></i><i></i><i></i></span><span>目录</span><span class="index-current" id="current-page">01</span></button>
<dialog id="lesson-index" aria-labelledby="index-title"><div class="dialog-top"><p>ICUC / IP DESIGN</p><button class="close-button" data-close="lesson-index" aria-label="关闭课堂目录">关闭 <span aria-hidden="true">×</span></button></div><h2 id="index-title">课堂目录</h2><p class="index-intro">从形象识别，到完整的角色系统。</p><label class="index-search" for="lesson-search">查找课件<input id="lesson-search" type="search" placeholder="记忆锚点、巴斯、配色…" autocomplete="off"></label><div class="search-results" id="search-results" hidden aria-live="polite"></div><nav id="chapter-list" aria-label="课程章节">${chapters.map(([n,t,p,d])=>`<a class="chapter-link" href="#${p}" data-jump="${p}"><span>${n}</span><div><strong>${t}</strong><small>${d}</small></div><span aria-hidden="true">↗</span></a>`).join('')}</nav><p class="index-bottom">79页 / 向下滚动阅读</p></dialog>
<dialog id="lightbox" aria-labelledby="lightbox-title"><div class="dialog-top"><p id="lightbox-title">角色设计图像</p><button class="close-button" data-close="lightbox" aria-label="关闭大图">返回课堂 <span aria-hidden="true">×</span></button></div><div class="lightbox-scroll"><img id="large-image" alt=""><p id="large-caption"></p></div><div class="zoom-controls" aria-label="大图缩放"><button id="zoom-out" aria-label="缩小大图">−</button><span id="zoom-level">适应窗口</span><button id="zoom-in" aria-label="放大大图">＋</button><button id="zoom-reset">还原</button></div></dialog>
<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'LearningResource',name:'角色观察档案｜IP角色设计',inLanguage:'zh-CN',learningResourceType:'课程讲义',description:'角色概念设计理论、视觉记忆锚点、巴斯光年案例与原创设计流程。'})}</script></body></html>`;
fs.writeFileSync(path.join(root,'index.html'),html,'utf8');
console.log(JSON.stringify({sections:lesson.length,originals:lesson.filter(s=>s.original).length,added:lesson.filter(s=>s.afterOriginal).length,bytes:Buffer.byteLength(html)}));
